version: '3.8'

services:
  server:
    build: ./docker/server
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - mensa-network

  client:
    build: ./docker/client
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - mensa-network

  database:
    image: postgres:17
    environment:
      POSTGRES_DB: mensa
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mensa-network

networks:
  mensa-network:
    driver: bridge

volumes:
  db_data:
