apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
type: Opaque
stringData:
  database.username: {{ .Values.secrets.database.username }}
  database.password: {{ .Values.secrets.database.password }}
  jwt.secret: {{ .Values.secrets.jwt.secret }}
