---
- name: Install ufw
  apt:
    name: ufw
    state: present

- name: Allow SSH
  ufw:
    rule: allow
    port: '22'

- name: Allow HTTP
  ufw:
    rule: allow
    port: '80'

- name: Allow application port
  ufw:
    rule: allow
    port: '8080'

- name: Enable firewall
  ufw:
    state: enabled
