name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker images
      run: |
        docker build -t mensa-server:${{ github.sha }} ./docker/server
        docker build -t mensa-client:${{ github.sha }} ./docker/client
    
    - name: Run tests with Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d
        sleep 30
        # Add your test commands here
        docker-compose down
    
    - name: Login to Container Registry
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Push to Registry
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag mensa-server:${{ github.sha }} ghcr.io/${{ github.repository }}/server:latest
        docker tag mensa-client:${{ github.sha }} ghcr.io/${{ github.repository }}/client:latest
        docker push ghcr.io/${{ github.repository }}/server:latest
        docker push ghcr.io/${{ github.repository }}/client:latest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Kubectl
      uses: azure/setup-kubectl@v3
    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/
        kubectl rollout status deployment/mensa-server
